import { Voice, StylePack, MusicPack, GeneratedVideo, PricingPlan } from "@/types/kutly";

export const VOICES: Voice[] = [
  {
    id: "simon",
    name: "Simon",
    gender: "male",
    accent: "British",
    style: "Authoritative Documentary",
    sampleText: "The Strait of Malacca is the single most critical maritime chokepoint in modern history.",
    isFavorite: true,
  },
  {
    id: "olivia",
    name: "Olivia",
    gender: "female",
    accent: "American",
    style: "Deep & Cinematic Storytelling",
    sampleText: "Deep beneath the ocean floor lies a geological secret that baffled scientists for decades.",
    isFavorite: true,
  },
  {
    id: "marcus",
    name: "Marcus",
    gender: "male",
    accent: "American",
    style: "Gravelly True Crime & Mystery",
    sampleText: "On a cold November night in 1974, a mystery unfolded that would never be fully solved.",
    isFavorite: false,
  },
  {
    id: "sarah",
    name: "Sarah",
    gender: "female",
    accent: "British",
    style: "Polished Tech & Science",
    sampleText: "Quantum computing is on the verge of breaking every standard encryption protocol.",
    isFavorite: true,
  },
  {
    id: "david",
    name: "David",
    gender: "male",
    accent: "American",
    style: "Energetic Business & Finance",
    sampleText: "How a tiny semiconductor startup grew into a three-trillion-dollar monopoly.",
    isFavorite: false,
  },
  {
    id: "emma",
    name: "Emma",
    gender: "female",
    accent: "Australian",
    style: "Warm Nature & Geography",
    sampleText: "Across the vast Australian outback, ancient ecosystems thrive in extreme isolation.",
    isFavorite: false,
  },
];

export const STYLE_PACKS: StylePack[] = [
  {
    id: "velvet",
    name: "Velvet",
    tag: "PREMIUM",
    description: "Deep luxury shadows, atmospheric contrast, subtle grain and filmic lighting.",
    colorScheme: ["#0E0C0B", "#D9482E", "#FF7E5F", "#1B1A17"],
    previewUrl: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "noir",
    name: "Noir",
    tag: "DEFAULT",
    description: "High-contrast monochrome with bold accent pops, dramatic lighting for mystery & crime.",
    colorScheme: ["#121212", "#FAFAF7", "#D9482E", "#2A2A2A"],
    previewUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "cinematic",
    name: "Cinematic 35mm",
    tag: "NEW",
    description: "Wide anamorphic ratios, rich warm grade, volumetric light and lens flare accents.",
    colorScheme: ["#0D1B2A", "#E0A96D", "#778DA9", "#1B263B"],
    previewUrl: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "modern_explainer",
    name: "Modern Explainer",
    description: "Clean isometric infographics, slick 3D motion typography, corporate high-tech look.",
    colorScheme: ["#0F172A", "#38BDF8", "#818CF8", "#1E293B"],
    previewUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk & Sci-Fi",
    description: "Neon glow lines, HUD overlays, high-energy futuristic motion graphics.",
    colorScheme: ["#090A0F", "#F43F5E", "#06B6D4", "#1E1B4B"],
    previewUrl: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=600&auto=format&fit=crop&q=80",
  },
];

export const MUSIC_PACKS: MusicPack[] = [
  { id: "the_investigator", name: "The Investigator", genre: "Suspense & Orchestral", tempo: "95 BPM" },
  { id: "ambient_dark", name: "Deep Ambient Noir", genre: "Atmospheric Drone", tempo: "70 BPM" },
  { id: "cinematic_epic", name: "Rise of Empires", genre: "Epic Cinematic Strings", tempo: "110 BPM" },
  { id: "lofi_focus", name: "Subtle Lo-Fi Documentary", genre: "Chill Background", tempo: "84 BPM" },
  { id: "tech_pulse", name: "Silicon Pulse", genre: "Modern Electronic", tempo: "120 BPM" },
];

export const INITIAL_VIDEOS: GeneratedVideo[] = [
  {
    id: "vid-malacca-1",
    title: "The Chokepoint That Controls 25% of Global Trade: The Malacca Dilemma",
    topic: "Why the Strait of Malacca is the most dangerous shipping bottleneck in modern geopolitics.",
    durationMinutes: 20,
    durationFormatted: "20:45",
    createdAt: "2 hours ago",
    status: "ready",
    thumbnailUrl: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&auto=format&fit=crop&q=80",
    aspectRatio: "16:9",
    voiceName: "Simon (British)",
    stylePackName: "Velvet",
    scriptSnippet: "Barely two kilometres wide at its narrowest, the Strait of Malacca is the single most important stretch of water on Earth. Over 94,000 vessels traverse this passage every single year...",
    seoTags: ["strait of malacca", "global trade", "geopolitics explained", "china malacca dilemma", "documentary"],
    viewsCount: 14200,
  },
  {
    id: "vid-nvidia-2",
    title: "How NVIDIA Bet Everything on a Technology Nobody Wanted (And Won)",
    topic: "The 30-year engineering gamble behind Jensen Huang and the AI hardware revolution.",
    durationMinutes: 14,
    durationFormatted: "14:12",
    createdAt: "Yesterday",
    status: "ready",
    thumbnailUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&auto=format&fit=crop&q=80",
    aspectRatio: "16:9",
    voiceName: "David (American)",
    stylePackName: "Cinematic 35mm",
    scriptSnippet: "In 2006, Wall Street thought Jensen Huang had lost his mind. NVIDIA had spent billions designing CUDA, a programming language for chips meant only for video games...",
    seoTags: ["nvidia", "jensen huang", "ai chip boom", "tech documentary", "business breakdown"],
    viewsCount: 28900,
  },
  {
    id: "vid-rome-3",
    title: "The Battle of Cannae: Hannibal's Masterpiece of Total Encirclement",
    topic: "How Hannibal Barca destroyed 80,000 Roman soldiers in a single afternoon.",
    durationMinutes: 30,
    durationFormatted: "29:50",
    createdAt: "3 days ago",
    status: "ready",
    thumbnailUrl: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&auto=format&fit=crop&q=80",
    aspectRatio: "16:9",
    voiceName: "Olivia (American)",
    stylePackName: "Noir",
    scriptSnippet: "On August 2nd, 216 BC, under the scorching heat of the southern Italian sun, the greatest military tactician of antiquity lured Rome into the ultimate trap...",
    seoTags: ["hannibal barca", "battle of cannae", "roman history", "ancient warfare", "military tactics"],
    viewsCount: 54100,
  },
];

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: "starter",
    name: "Starter",
    priceMonthly: 29,
    priceAnnual: 24,
    credits: 600,
    minutesProduction: 60,
    maxVideoDuration: 30,
    concurrency: "1 concurrent render",
    features: [
      "Up to 9 long-form videos / mo",
      "60 min full AI production or 75 min editing-only",
      "1080p Full HD video export",
      "Studio AI Voiceovers & Scriptwriting",
      "Automatic YouTube thumbnail & SEO tags",
      "Standard video processing speed",
      "Email support",
    ],
  },
  {
    id: "creator",
    name: "Creator",
    priceMonthly: 83,
    priceAnnual: 69,
    credits: 2000,
    minutesProduction: 200,
    maxVideoDuration: 30,
    concurrency: "2 concurrent renders",
    popular: true,
    features: [
      "Up to 31 long-form videos / mo",
      "200 min full AI production or 250 min editing-only",
      "Everything in Starter",
      "2× Faster high-priority video processing",
      "2 concurrent generations",
      "Access to all Premium Style Packs & Fonts",
      "Auto-publish to linked YouTube channels",
      "Priority email support",
    ],
  },
  {
    id: "studio",
    name: "Studio",
    priceMonthly: 249,
    priceAnnual: 199,
    credits: 6000,
    minutesProduction: 600,
    maxVideoDuration: 30,
    concurrency: "5 concurrent renders",
    features: [
      "Up to 90 long-form videos / mo",
      "600 min full AI production or 750 min editing-only",
      "Everything in Creator",
      "5× Concurrency for high-volume channels",
      "Instant top-tier GPU render cluster",
      "Custom voice cloning (your own voice)",
      "Priority access to new AI models",
      "Direct Slack support with engineering team",
    ],
  },
  {
    id: "enterprise",
    name: "Enterprise",
    priceMonthly: 999,
    priceAnnual: 849,
    credits: 24000,
    minutesProduction: 2400,
    maxVideoDuration: 60,
    concurrency: "Unlimited concurrent renders",
    features: [
      "Custom credit volume (100k+ credits)",
      "Unlimited concurrency",
      "4K Ultra-HD video render pipeline",
      "Dedicated account manager & SLA",
      "Custom workflow integrations & API access",
      "Custom brand typography & assets library",
      "Multi-seat team workspace",
    ],
  },
];

export const PROMPT_STARTERS = [
  "Why the Roman Empire never industrialized despite having steam power concepts",
  "The psychology behind why casinos have no windows and use algorithmic lighting",
  "How Taiwan became the world's most irreplaceable island through TSMC",
  "The unsolved mystery of Flight MH370: The data, radar tracks and satellite pings",
  "The secret economics of commercial airlines: How loyalty programs make more than flights",
  "How the Dutch East India Company became richer than Apple, Amazon and Google combined",
];
