"use client";

import React, { useState } from "react";
import { PRICING_PLANS } from "@/lib/data";
import { Check, Zap, HelpCircle, ArrowRight } from "lucide-react";

interface PricingViewProps {
  onSelectPlan: (planId: string) => void;
  onAddCredits: (amount: number) => void;
}

export function PricingView({ onSelectPlan, onAddCredits }: PricingViewProps) {
  const [annual, setAnnual] = useState(true);

  const faqs = [
    {
      q: "What does 1 credit equal?",
      a: "1 credit equals 1 minute of AI scriptwriting, research, audio voiceover and motion design rendering. For example, a full 20-minute video uses ~60-85 credits depending on custom styling.",
    },
    {
      q: "Can I use my own voice for videos?",
      a: "Yes! With our 'Voiceover-to-Video' mode or custom voice cloning (Studio plan), you can upload your own narration or clone your vocal identity.",
    },
    {
      q: "Are the generated videos monetizable on YouTube?",
      a: "100% yes. All AI voices, music licenses, visual styles, and scripts generated by Kutly are commercial-cleared for YouTube partner monetization.",
    },
    {
      q: "What video quality is exported?",
      a: "All plans include 1080p Full HD at 60 FPS. Enterprise accounts have access to 4K Ultra-HD pipelines.",
    },
  ];

  return (
    <div className="w-full max-w-6xl mx-auto p-6 space-y-12">
      {/* Header */}
      <div className="text-center space-y-3 max-w-2xl mx-auto">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#D9482E]/10 border border-[#D9482E]/20 text-[#FAFAF7] text-xs font-mono">
          <Zap className="w-3.5 h-3.5 text-[#D9482E]" />
          <span>Transparent Creator Pricing</span>
        </div>
        <h2 className="text-2xl sm:text-4xl font-bold tracking-tight text-[#FAFAF7]">
          Production capacity that scales with your channel
        </h2>
        <p className="text-xs sm:text-sm text-[#8C8985]">
          Generate dozens of documentary-grade videos without hiring editors, voice actors, or motion designers.
        </p>

        {/* Monthly / Annual Toggle */}
        <div className="flex items-center justify-center gap-3 pt-4">
          <span className={`text-xs ${!annual ? "text-white font-semibold" : "text-[#8C8985]"}`}>
            Monthly Billing
          </span>
          <button
            type="button"
            onClick={() => setAnnual(!annual)}
            className={`relative inline-flex h-6 w-12 items-center rounded-full transition-colors cursor-pointer ${
              annual ? "bg-[#D9482E]" : "bg-[#252320]"
            }`}
          >
            <span
              className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${
                annual ? "translate-x-7" : "translate-x-1"
              }`}
            />
          </button>
          <span className={`text-xs flex items-center gap-1.5 ${annual ? "text-white font-semibold" : "text-[#8C8985]"}`}>
            Annual Billing
            <span className="px-2 py-0.5 rounded-full bg-emerald-500/20 text-emerald-400 text-[10px] font-mono font-bold uppercase">
              Save 20%
            </span>
          </span>
        </div>
      </div>

      {/* Pricing Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {PRICING_PLANS.map((plan) => {
          const price = annual ? plan.priceAnnual : plan.priceMonthly;
          const isPopular = plan.popular;

          return (
            <div
              key={plan.id}
              className={`relative rounded-2xl p-6 flex flex-col justify-between transition-all duration-300 ${
                isPopular
                  ? "bg-[#1C1A18] border-2 border-[#D9482E] shadow-2xl shadow-[#D9482E]/15 -translate-y-1"
                  : "bg-[#151312] border border-white/8 hover:border-white/20"
              }`}
            >
              {isPopular && (
                <span className="absolute -top-3 left-1/2 -translate-x-1/2 px-3 py-0.5 rounded-full bg-[#D9482E] text-white text-[10px] font-mono font-bold uppercase tracking-wider shadow-md">
                  MOST POPULAR
                </span>
              )}

              <div>
                <h3 className="text-lg font-bold text-[#FAFAF7]">{plan.name}</h3>
                <div className="mt-3 flex items-baseline gap-1">
                  <span className="text-3xl font-extrabold text-[#FAFAF7] font-mono">
                    ${price}
                  </span>
                  <span className="text-xs text-[#8C8985]">/ month</span>
                </div>

                <div className="mt-4 p-3 rounded-xl bg-[#252320] border border-white/6 space-y-1">
                  <div className="flex items-center justify-between text-xs">
                    <span className="text-[#8C8985]">Monthly Credits</span>
                    <span className="font-mono font-bold text-[#FF7E5F]">
                      {plan.credits.toLocaleString()}
                    </span>
                  </div>
                  <p className="text-[11px] text-[#8C8985]">{plan.concurrency}</p>
                </div>

                {/* Features List */}
                <ul className="mt-6 space-y-2.5 text-xs text-[#A3A09A]">
                  {plan.features.map((feat, idx) => (
                    <li key={idx} className="flex items-start gap-2.5">
                      <Check className="w-4 h-4 text-[#D9482E] shrink-0 mt-0.5" />
                      <span className="leading-snug">{feat}</span>
                    </li>
                  ))}
                </ul>
              </div>

              <div className="mt-8 pt-4 border-t border-white/6">
                <button
                  onClick={() => {
                    onSelectPlan(plan.id);
                    onAddCredits(plan.credits);
                    alert(`Subscribed to ${plan.name} plan! Added ${plan.credits} credits to your account.`);
                  }}
                  className={`w-full py-2.5 px-4 rounded-xl font-semibold text-xs transition-all cursor-pointer flex items-center justify-center gap-2 ${
                    isPopular
                      ? "bg-gradient-to-r from-[#D9482E] to-[#FF7E5F] text-white hover:opacity-95 shadow-md shadow-[#D9482E]/25"
                      : "bg-[#252320] hover:bg-white/10 text-white"
                  }`}
                >
                  <span>Select {plan.name}</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>
          );
        })}
      </div>

      {/* Credit Top-up Box */}
      <div className="rounded-2xl bg-[#1C1A18] border border-white/8 p-6 flex flex-col md:flex-row items-center justify-between gap-6">
        <div>
          <h3 className="text-base font-bold text-[#FAFAF7] flex items-center gap-2">
            <Zap className="w-5 h-5 text-[#D9482E]" />
            Need more credits without upgrading?
          </h3>
          <p className="text-xs text-[#8C8985] mt-1">
            Top up credits on-demand at any time. Extra credits never expire.
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-3">
          {[
            { credits: 500, price: "$25" },
            { credits: 1500, price: "$65" },
            { credits: 5000, price: "$180" },
          ].map((topup) => (
            <button
              key={topup.credits}
              onClick={() => {
                onAddCredits(topup.credits);
                alert(`Added ${topup.credits} credits to your workspace!`);
              }}
              className="px-4 py-2 rounded-xl bg-[#252320] hover:bg-[#D9482E] text-white border border-white/8 text-xs font-semibold transition-all cursor-pointer group"
            >
              <span className="font-mono">+{topup.credits} credits</span>
              <span className="text-[#8C8985] group-hover:text-white ml-2">({topup.price})</span>
            </button>
          ))}
        </div>
      </div>

      {/* FAQs */}
      <div className="space-y-6 pt-4 border-t border-white/8">
        <h3 className="text-lg font-bold text-[#FAFAF7] text-center">Frequently Asked Questions</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {faqs.map((faq, idx) => (
            <div key={idx} className="p-4 rounded-xl bg-[#151312] border border-white/6 space-y-1.5">
              <h4 className="text-xs font-semibold text-[#FAFAF7] flex items-center gap-2">
                <HelpCircle className="w-4 h-4 text-[#FF7E5F] shrink-0" />
                {faq.q}
              </h4>
              <p className="text-xs text-[#8C8985] leading-relaxed pl-6">{faq.a}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
